version: 2

defaults: &defaults
  working_directory: ~/synology-typescript-api
  docker:
    - image: circleci/node:12.10.0

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run:
          name: Yarn Install
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Test
          command: npm test
      - persist_to_workspace:
          root: ~/synology-typescript-api
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/synology-typescript-api
      - run:
          name: Create npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/synology-typescript-api/.npmrc
      - run:
          name: Publish
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
